name: Release Build

on:
  push:
    branches: [ core/** ]
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore Rhino.Mocks.sln

      - name: Build the Solution
        run: |
          $tag = ${env:GITHUB_REF} -replace 'refs/tags/v',''
          msbuild Rhino.Mocks.sln /p:Configuration=Release /p:Version=${tag} /p:AssemblyVersion=${tag} /p:FileVersion=${tag}

      - name: ILRepack assemblies
        run: |
          .\ilrepack.ps1 "Rhino.Mocks\bin\release\net35\"
          .\ilrepack.ps1 "Rhino.Mocks\bin\release\netcoreapp3.1\"

      - name: Pack
        run: |
          $tag = ${env:GITHUB_REF} -replace 'refs/tags/v',''
          dotnet pack --no-restore --no-build /p:Version=${tag} -o .\Rhino.Mocks\bin\release\ .\Rhino.Mocks\Rhino.Mocks.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Rhino.Mocks
          path: Rhino.Mocks\bin\release\*.nupkg
